/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practicas;

import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author macpro2
 */
public class Practica6 extends javax.swing.JFrame {

    /**
     * Creates new form Practica6
     */
    public Practica6() {
        initComponents();
        
        DefaultComboBoxModel cbm = new DefaultComboBoxModel();
        
        cbm = (DefaultComboBoxModel) this.cbLista1.getModel();
        this.cbLista2.setModel(cbm);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOriginal = new javax.swing.ButtonGroup();
        bgEspejo = new javax.swing.ButtonGroup();
        lblOriginal = new javax.swing.JLabel();
        rbOpcion1 = new javax.swing.JRadioButton();
        rbOpcion2 = new javax.swing.JRadioButton();
        rbOpcion3 = new javax.swing.JRadioButton();
        chkOpcion4 = new javax.swing.JCheckBox();
        chkOpcion5 = new javax.swing.JCheckBox();
        chkOpcion6 = new javax.swing.JCheckBox();
        tfTexo1 = new javax.swing.JTextField();
        cbLista1 = new javax.swing.JComboBox<>();
        spValor1 = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        lblEspejo = new javax.swing.JLabel();
        rbOpcion11 = new javax.swing.JRadioButton();
        rbOpcion22 = new javax.swing.JRadioButton();
        rbOpcion33 = new javax.swing.JRadioButton();
        chkOpcion44 = new javax.swing.JCheckBox();
        chkOpcion55 = new javax.swing.JCheckBox();
        chkOpcion66 = new javax.swing.JCheckBox();
        tfTexo2 = new javax.swing.JTextField();
        cbLista2 = new javax.swing.JComboBox<>();
        spValor2 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblOriginal.setText("Original");

        bgOriginal.add(rbOpcion1);
        rbOpcion1.setSelected(true);
        rbOpcion1.setText("Opcion 1");
        rbOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOpcion1ActionPerformed(evt);
            }
        });

        bgOriginal.add(rbOpcion2);
        rbOpcion2.setText("Opcion 2");
        rbOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOpcion2ActionPerformed(evt);
            }
        });

        bgOriginal.add(rbOpcion3);
        rbOpcion3.setText("Opcion 3");
        rbOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOpcion3ActionPerformed(evt);
            }
        });

        chkOpcion4.setText("Opcion 4");
        chkOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOpcion4ActionPerformed(evt);
            }
        });

        chkOpcion5.setText("Opcion 5");
        chkOpcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOpcion5ActionPerformed(evt);
            }
        });

        chkOpcion6.setText("Opcion 6");
        chkOpcion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOpcion6ActionPerformed(evt);
            }
        });

        tfTexo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTexo1KeyReleased(evt);
            }
        });

        spValor1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spValor1StateChanged(evt);
            }
        });

        lblEspejo.setText("Espejo");

        bgEspejo.add(rbOpcion11);
        rbOpcion11.setSelected(true);
        rbOpcion11.setText("Opcion 1");
        rbOpcion11.setEnabled(false);

        bgEspejo.add(rbOpcion22);
        rbOpcion22.setText("Opcion 2");
        rbOpcion22.setEnabled(false);

        bgEspejo.add(rbOpcion33);
        rbOpcion33.setText("Opcion 3");
        rbOpcion33.setEnabled(false);

        chkOpcion44.setText("Opcion 4");
        chkOpcion44.setEnabled(false);

        chkOpcion55.setText("Opcion 5");
        chkOpcion55.setEnabled(false);

        chkOpcion66.setText("Opcion 6");
        chkOpcion66.setEnabled(false);

        tfTexo2.setEnabled(false);

        cbLista2.setEnabled(false);

        spValor2.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblOriginal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbOpcion1)
                            .addComponent(rbOpcion3)
                            .addComponent(rbOpcion2))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkOpcion4)
                            .addComponent(chkOpcion5)
                            .addComponent(chkOpcion6))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTexo1)
                            .addComponent(cbLista1, 0, 184, Short.MAX_VALUE)
                            .addComponent(spValor1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEspejo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbOpcion11)
                                    .addComponent(rbOpcion33)
                                    .addComponent(rbOpcion22))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkOpcion44)
                                    .addComponent(chkOpcion55)
                                    .addComponent(chkOpcion66))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfTexo2)
                                    .addComponent(cbLista2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblOriginal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcion1)
                    .addComponent(chkOpcion4)
                    .addComponent(tfTexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcion2)
                    .addComponent(chkOpcion5)
                    .addComponent(cbLista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcion3)
                    .addComponent(chkOpcion6)
                    .addComponent(spValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblEspejo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcion11)
                    .addComponent(chkOpcion44)
                    .addComponent(tfTexo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcion22)
                    .addComponent(chkOpcion55)
                    .addComponent(cbLista2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcion33)
                    .addComponent(chkOpcion66)
                    .addComponent(spValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTexo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTexo1KeyReleased
        String texto = this.tfTexo1.getText();
        this.tfTexo2.setText(texto);
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !texto.isEmpty()){
            int n = this.cbLista1.getItemCount();
            boolean found = false;
            for(int i=0; i<n; i++){
                if (this.cbLista1.getItemAt(i).equals(texto)){
                    found = true;
                    break;
                }
            }
           
            if (!found){
                this.cbLista1.addItem(texto);
            }  
        }
    }//GEN-LAST:event_tfTexo1KeyReleased

    private void rbOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcion1ActionPerformed
        this.rbOpcion11.setSelected(true);
    }//GEN-LAST:event_rbOpcion1ActionPerformed

    private void rbOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcion2ActionPerformed
        this.rbOpcion22.setSelected(true);
    }//GEN-LAST:event_rbOpcion2ActionPerformed

    private void rbOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcion3ActionPerformed
        this.rbOpcion33.setSelected(true);
    }//GEN-LAST:event_rbOpcion3ActionPerformed

    private void chkOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOpcion4ActionPerformed
        this.chkOpcion44.setSelected(this.chkOpcion4.isSelected());
    }//GEN-LAST:event_chkOpcion4ActionPerformed

    private void chkOpcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOpcion5ActionPerformed
        this.chkOpcion55.setSelected(this.chkOpcion5.isSelected());
    }//GEN-LAST:event_chkOpcion5ActionPerformed

    private void chkOpcion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOpcion6ActionPerformed
        this.chkOpcion66.setSelected(this.chkOpcion6.isSelected());
    }//GEN-LAST:event_chkOpcion6ActionPerformed

    private void spValor1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spValor1StateChanged
        this.spValor2.setValue(this.spValor1.getValue());
    }//GEN-LAST:event_spValor1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEspejo;
    private javax.swing.ButtonGroup bgOriginal;
    private javax.swing.JComboBox<String> cbLista1;
    private javax.swing.JComboBox<String> cbLista2;
    private javax.swing.JCheckBox chkOpcion4;
    private javax.swing.JCheckBox chkOpcion44;
    private javax.swing.JCheckBox chkOpcion5;
    private javax.swing.JCheckBox chkOpcion55;
    private javax.swing.JCheckBox chkOpcion6;
    private javax.swing.JCheckBox chkOpcion66;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEspejo;
    private javax.swing.JLabel lblOriginal;
    private javax.swing.JRadioButton rbOpcion1;
    private javax.swing.JRadioButton rbOpcion11;
    private javax.swing.JRadioButton rbOpcion2;
    private javax.swing.JRadioButton rbOpcion22;
    private javax.swing.JRadioButton rbOpcion3;
    private javax.swing.JRadioButton rbOpcion33;
    private javax.swing.JSpinner spValor1;
    private javax.swing.JSpinner spValor2;
    private javax.swing.JTextField tfTexo1;
    private javax.swing.JTextField tfTexo2;
    // End of variables declaration//GEN-END:variables
}
